### ISSUE TITLE
[Request] Roll as Blind when Trait is "Secret"

### ISSUE THREAD

**Issue by jocolamarco** [MarkPearce/SkillActionDialog#6]
If the Skill Action has a trait of "secret", the roll should be blind. Example: Recall Knowledge
Is this possible to do?

**Comment by MarkPearce** [comment]
Hmm... I'm not much of an programmer.  I don't find it to be that big a deal I use the dice tray mod that lets the players set their roll type manually. https://foundryvtt.com/packages/dice-calculator

if someone can give me a hint, docs, or code example i'd be happy to make a change otherwise i don't think i'll fix this.

**Comment by MarkPearce** [comment]
I've learned enough to now fix recall knowledge to add the 'secret' trait.

Other skills that use use system action like perception or hide should do this already. If there's other skills you find that need it let me know.
